### ISSUE TITLE
Give users some freedom

### ISSUE THREAD

**Issue by ghost** [Sayo-nika/autobuild.sh#2]
Why is Minio S3 Client had to be installed anyway?
What if I don't want to download anything because I already had RenPy and DDLC archives or my server/cloud/cl doesn't allow it?
How can I make this script less/more verbose?

~~**Just Monio**~~

**Comment by sr229** [comment]
this is a limitation of the current version sadly, but I plan to actually make it more accessible to people by allowing their own clouds - but that's too much work. I'd be glad to accept PRs though.

**Comment by sr229** [comment]
Found a solution to parse local DDLC dirs, and have Minio S3 as a fallback method.

**Comment by sr229** [comment]
Resolved in #3

**Comment by ghost** [comment]
How about verbosity?
Average build scripts only print errors in production to help developers faster know where is a problem and resolve it.

**Comment by sr229** [comment]
Loglevels are not implemented. It's verbose by default. @45Green
